#!/usr/bin/env python

Import('*')
import sys

envl = env.Clone()

envl.Append(LIBS=['rt'])
envl.Append(CPPPATH=['../'])
envl.Append(CPPFLAGS=['-std=c++0x'])

if not envl.GetOption('clean'):
	envl.ParseConfig('pkg-config --cflags --libs $GLIB_PC')
	envl.ParseConfig('pkg-config --cflags --libs $GTHREAD_PC')
	envl.ParseConfig('pkg-config --cflags --libs $GDK_PC')
	envl.ParseConfig('pkg-config --cflags --libs $LUA_PC')

sources = envl.Glob('*.cpp')

objects = []

rendering_engine = envl.SharedLibrary(
	'sm_render_engine1',
	source = [sources, objects])

Return(['rendering_engine'])
